avoid "error matching regexp" after pcre updates
Now stores the pcre_version before attr_items.size, and the plain
regex-string right after each compiled regex. If current pcre version
differs on load, we recompile. If we have the same version, we use the
precompiled patterns.

For e.g. nno-nob's t1x, there is no speed difference on precompiled vs
recompile, though perhaps other tNx's are a lot slower to load.

Note: you'll still have to recompile your transfer files one last time,
since this changes the transfer bin format. If you don't, you'll get a
message like

    Error: conversion error

on trying to translate.